main: me.unfamousthomas.IslandClashDuels.IslandClashDuels
name: IslandClashDuels
version: 1.0.0
author: UnfamousThomas
description: A plugin!
commands:
  duel:
    description: Duel someone
    usage: /duel (player)
